version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8100:8100"
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3100:80"
    depends_on:
      - backend
